### ISSUE TITLE
Move CSSs inside the repo

### ISSUE THREAD

**Issue by suhr** [elves/elvish.io#1]
When the styles are inside a blog generator, editing them is not that simple and nice. Also, I don't think that *including* them inside the HTML is a good idea.

> TODO: Slideshow

https://asciinema.org/

**Comment by xiaq** [comment]
Thanks for the suggestions.

1. It's indeed better to have CSS in this repo instead in genblog. The thing is that I have been avoiding dealing with any kind of assets in genblog and CSS is, a kind of asset.

2. The slideshow has been implemented.

**Comment by xiaq** [comment]
Fixed in f0e05d489deda4cdd28dbc13ed843cf0280cc1e7.
