### ISSUE TITLE
Documentation for changing default shell

### ISSUE THREAD

**Issue by marcdel** [elves/elvish.io#9]
It wasn't obvious to me how to change my default shell to elvish. It might be helpful to have this information in the docs somewhere. I'd be happy to submit a PR, but I'm not sure where the best place for this would be.

For reference, what worked for me was: `echo $(which elvish) | sudo tee -a /etc/shells && chsh -s $(which elvish)`.

**Comment by zzamboni** [comment]
@marcdel the instructions should be split in two steps: add the new shell to `/etc/shells` (which should be done only once), and then use `chsh` to change the shell of any users.

**Comment by xiaq** [comment]
This is now tracked in https://github.com/elves/elvish/issues/694
